### ISSUE TITLE
Phasmophobia auto splitter does not start/split correctly (sometimes)

### ISSUE THREAD

**Issue by LE-M-ON** [just-ero/AutoSplitTools#2]
---
## *Describe your Issue*

If there is any especially weird behavior with the timer, please describe what is happening:  
- The auto splitter works perfectly the majority of the time, however it will sometimes split soon after starting. Often times it will split 0.01s after starting but can split up to 3 seconds later. I checked my recordings and could see that I definitely did not accidentally hit my split key any time when this would happen. I also checked to see if the auto splitter was enabled in both 'layout' and 'edit splits' and it was not. 
- The only info I can provide would be that each time the timer would start, I would be spamming the 'S' and 'D' keys while also flicking my mouse to the right quickly at the same time that it should start the timer (I have a keyboard visualiser visible in all my recordings and so this can be seen in this video: https://youtu.be/ZV2MXD9wGfg ). Additionally, each time was only solo and in 'training'. I am unsure if it can happen in multiplayer, on other maps or without any key presses. 

---
## *Causes and Fixes*
(*for experienced users only*)

- I do not know what might cause/fix the problem.
- There was an update on the same day that the autosplitter was updated, but I am unsure if the update was built with this in mind...

**Comment by just-ero** [comment]
Hey @LE-M-ON! I believe I know the issue as to why this behavior happens – or at least I have a suspicion. It's most likely because `vars.Stopwatch` does not get its time reset if the user resets the timer manually. The stopwatch is used to delay the split/reset at the end of an attempt since `LoadingBackToMenu` does not perfectly correspond to the actual loading screen.  
Could you see if this is the case? As in, does the incorret behavior only happen when you've previously reset the timer manually without waiting for the atomatic reset?  

I can't work on a fix for the coming days since I'm working on another project as well as university. Please understand!

**Comment by LE-M-ON** [comment]
> Hey @LE-M-ON! I believe I know the issue as to why this behavior happens – or at least I have a suspicion. It's most likely because `vars.Stopwatch` does not get its time reset if the user resets the timer manually. The stopwatch is used to delay the split/reset at the end of an attempt since `LoadingBackToMenu` does not perfectly correspond to the actual loading screen.
> Could you see if this is the case? As in, does the incorrect behavior only happen when you've previously reset the timer manually without waiting for the automatic reset?


That does seem like the problem. I have tested just now, and whenever I didn't reset it would not happen, but it would sometimes happen when I DID reset.

**Comment by just-ero** [comment]
Hey. Can you give the autosplitter a try now?

**Comment by LE-M-ON** [comment]
Hey. That seems to have done the trick! Works perfectly now. Thank you!
